version: '2'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_USER: postgres
      POSTGRES_DB: enginedb
    restart: always    
  server:
    build: ./server
    user: nobody
    volumes:       
      - ./server:/erss
    command: ./engine
    ports:
      - "12345:12345"
    expose:
      - "12345"
    depends_on:
      - db
